### ISSUE TITLE
Problem in Jupyter Notebook when trying to GSP

### ISSUE THREAD

**Issue by Jotivirix** [jacksonpradolima/gsp-py#1]
Hello! I am working on Jupyter Notebook through Anaconda

I am trying to do GSP over a list. My list of transactions looks like
[['HTML/CSS', 'Java', 'JavaScript', 'Python'],
 ['C++', 'HTML/CSS', 'Python'],
 ['HTML/CSS'],
 ['C', 'C++', 'C#', 'Python', 'SQL'],
 ['C++', 'HTML/CSS', 'Java', 'JavaScript', 'Python', 'SQL', 'VBA'],
 ['Java', 'R', 'SQL']]

And when trying to GSP(transactions).search(0.3) --> This means support 0.3

I got an error saying AttributeError: module '__main__' has no attribute '__spec__'

I have used this library before and nothing happens but now it's happening and I don't know how to fix it

Can anyone help me?

Thanks! ;)

![image](https://user-images.githubusercontent.com/15690713/104814931-c653c880-5811-11eb-9646-05d1a69644a0.png)
![image](https://user-images.githubusercontent.com/15690713/104814935-ca7fe600-5811-11eb-9163-740ff4e6abac.png)
![image](https://user-images.githubusercontent.com/15690713/104814937-cc49a980-5811-11eb-9d40-af4c0dd74f8c.png)

**Comment by Jotivirix** [comment]
Hi man! I have just got fixed.

I have a line in the start of the script that says %reset

I removed it and... all perfect!

**Comment by jacksonpradolima** [comment]
Perfect
